FROM python:3.8-slim

WORKDIR /app
COPY . .

RUN mkdir encode grouped source
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install -r requirements.txt

ENTRYPOINT [ "python" ]
CMD ["app.py"]
